openapi: 3.0.3
info:
  title: STD23058 - TD1
  version: '1.0.0'
servers:
  - url: https://localhost.std23058.com
paths:
  /customers:
    get:
      responses:
        200:
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    age:
                      type: integer

components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
